#### Employee API

#### Get All Employees
GET http://localhost:3000/api/employees

#### Get Employee
GET http://localhost:3000/api/employees/1

#### Add Employee
POST http://localhost:3000/api/employees
content-type: application/json

{
    "Id": 0,
    "Code": "CT8000",
    "Name": "Bucky Barns",
    "Job": "Manager",
    "Salary": 30000,
    "Department": "Operations"
}

#### Update Employee
PUT http://localhost:3000/api/employees/32
content-type: application/json

{
    "Id": 32,
    "Code": "CT9000",
    "Name": "Bucky Barns",
    "Job": "Manager",
    "Salary": 30000,
    "Department": "Operations"
}

#### Delete Employee
DELETE http://localhost:3000/api/employees/32