#### Employee API

#### Get Employees Status
GET http://localhost:3000/api/employees/status

#### Search Employees
GET http://localhost:3000/api/employees/search?name=jo

#### Employee Summary
GET http://localhost:3000/api/employees/summary

#### Add Many Employees
POST http://localhost:3000/api/employees/many
content-type: application/json

[
    {
        "Id": 0,
        "Code": "CT8100",
        "Name": "Bruce Banner",
        "Job": "Salesman",
        "Salary": 20000,
        "Department": "Sales"
    },
    {
        "Id": 0,
        "Code": "CT8200",
        "Name": "Clint",
        "Job": "Salesman",
        "Salary": 20000,
        "Department": "Sales"
    }
]

#### Get All Employees
GET http://localhost:3000/api/employees

#### Get Employee
GET http://localhost:3000/api/employees/1

#### Add Employee
POST http://localhost:3000/api/employees
content-type: application/json

{
    "Id": 0,
    "Code": "CT8000",
    "Name": "Bucky Barns",
    "Job": "Manager",
    "Salary": 30000,
    "Department": "Operations"
}

#### Update Employee
PUT http://localhost:3000/api/employees/32
content-type: application/json

{
    "Id": 32,
    "Code": "CT9000",
    "Name": "Bucky Barns",
    "Job": "Manager",
    "Salary": 30000,
    "Department": "Operations"
}

#### Delete Employee
DELETE http://localhost:3000/api/employees/32